#!/bin/bash

set -e

case "$1" in

   configure)
   	# Apache
	a2dissite default
	a2ensite freenet-router
	a2ensite freenet-router-ssl	
	mkdir -p /var/log/apache2
	chown root:adm /var/log/apache2
	chmod 750 /var/log/apache2 
	a2enmod ssl
        a2enmod rewrite
	a2enmod actions 
	a2enmod alias 
        a2enmod fastcgi
	service apache2 restart
	service php5-fpm restart

	if ! id -u freenet-web >/dev/null 2>&1; then
		adduser --quiet --home /var/www/freenet-router --shell /bin/false --disabled-password -gecos "" freenet-web
	fi

	chown -R freenet-web:freenet-web /var/www/freenet-router
   ;;

   *)
      echo "postinst called with unknown argument \`\$1'" >&2
   ;;

esac

exit 0

