#!/bin/bash

set -e

case "$1" in

   configure)
   	# Apache
	a2dissite 000-default
	a2ensite freenet-router
	a2ensite freenet-router-ssl	
	mkdir -p /var/log/apache2
	chown root:adm /var/log/apache2
	chmod 750 /var/log/apache2 
	a2enmod ssl
        a2enmod rewrite
	a2enmod actions 
	a2enmod alias 
	service apache2 restart

	chown -R www-data:www-data /var/www/freenet-router
	chown root:root /etc/sudoers.d/freenet-router-sudoers

	# Lets leave the initial daemons generation on the web interface
        rm -f /etc/quagga/daemons
   ;;

   *)
      echo "postinst called with unknown argument \`\$1'" >&2
   ;;

esac

exit 0

